import:
  - ~/.config/alacritty/theme/tokyo-night.yaml

env:
  TERM: alacritty

window:
  dynamic_padding: true
  decorations: none
  #opacity: 1.0

  #title: Alacritty
  dynamic_title: true
  decorations_theme_variant: dark

  scrolling:
    history: 10000
  multiplier: 3
  padding:
    x: 8
    y: 0

font:
  size: 10
  normal:
    family: JetBrainsMono Nerd Font
  offset:
    x: 0
    y: 2

  glyph_offset:
    x: 0
    y: 1

  builtin_box_drawing: true
  draw_bold_text_with_bright_colors: false

# When set to `true`, selected text will be copied to the primary clipboard.
#save_to_clipboard: false

cursor:
  style:
    shape: Beam
    blinking: Always
    blink_interval: 750
    blink_timeout: 5

  thickness: 0.15
  live_config_reload: false

shell:
  program: /usr/bin/fish
  args:
    - --login
